import streamlit as st
import pandas as pd
import plotly.express as px

st.markdown("<h1 style='text-align: center;'>Model Comparison</h1>", unsafe_allow_html=True)

#Benchmarks from Kaggle leaderboard, retrieved manually

KAGGLE_TOP_RMSE = 0.479
KAGGLE_LEADERBOARD_MEDIAN_RMSE = 0.580

def load_data():
    # Load results generated by models from csvs
    try:
        df_all = pd.read_csv("data/all_results.csv")
    except FileNotFoundError:
        st.error("File 'data/all_results.csv' not found. Or you're launching the streamlit app from the wrong directory. See README for troubleshooting.")
        return None

    try:
        df_summary = pd.read_csv("data/summary.csv")
    except FileNotFoundError:
        st.error("File 'data/summary.csv' not found. Or you're launching the streamlit app from the wrong directory. See README for troubleshooting.")
        return None
        
    # Clean model names, sometimes there are stray white spaces, depending on which notebook generated the predictions
    df_summary['model'] = df_summary['model'].str.strip()
    df_all['model_type'] = df_all['model_type'].str.strip()
        
    names_dict_a = {
        'CNN': 'CNN (Neural Net)',
        'CNN-particle filter': 'PF CNN',
        'Particle Filter': 'PF Baseline',
        'Transformer-particle filter': 'PF Transformer',
        'Transformer': 'Transformer'
    }
    
    names_dict_b = {
        'neural_net': 'CNN (Neural Net)',
        'pf_neural_net': 'PF CNN',
        'pf_none': 'PF Baseline',
        'pf_transformer': 'PF Transformer',
        'transformer': 'Transformer'
    }
    
    df_summary['model'] = df_summary['model'].replace(names_dict_a)
    df_all['model_type'] = df_all['model_type'].replace(names_dict_b)
    
    return df_all, df_summary

all_sample_df, summary_df = load_data()


# Fixed Colour scheme

model_colour_scheme = {
    'CNN (Neural Net)': '#66c2a5',
    'PF CNN': '#fc8d62',
    'PF Baseline': '#8da0cb',
    'PF Transformer': '#e78ac3',
    'Transformer': '#a6d854',
    'Kaggle Top': '#FFD700',
    'Kaggle Median': '#C0C0C0'
}

st.header("1. Overall Performance (RMSE)")

st.caption("Our five models, the three base models, the Particle Filter (Baseline), the CNN (Neural Network), the Transformer, the Particle Filter - Transformer hybrid, and the Particle Filter - CNN hybrid models.")
# Add benchmarks to df
benchmarks_df = pd.DataFrame({
    'model': ['Kaggle Top', 'Kaggle Median'],
    'rmse': [KAGGLE_TOP_RMSE, KAGGLE_LEADERBOARD_MEDIAN_RMSE]
})
comparison_df = pd.concat([summary_df[['model', 'rmse']], benchmarks_df], ignore_index=True)
comparison_df = comparison_df.sort_values('rmse', ascending=False)

# Horizontal Bar Chart
hbar_fig1 = px.bar(
    comparison_df,
    x="rmse",
    y="model",
    orientation='h',
    text_auto='.3f', # Displays numbers on bars
    color="model",
    color_discrete_map=model_colour_scheme, #Fixed colour scheme
    title="Our Models vs Kaggle Benchmarks"
)

hbar_fig1.update_layout(showlegend=False, xaxis_title="RMSE (Lower is Better)", yaxis_title="", xaxis=dict(showgrid=True))
st.plotly_chart(hbar_fig1, use_container_width=True)

st.markdown("---")

# Box Plot
st.header("2. Error Distribution Box Plot")
st.caption("Comparison of model performance by L2 distance error distribution across 5 different models.")

box_fig2 = px.box(
    all_sample_df,
    x="error_l2",
    y="model_type",
    color="model_type",
    color_discrete_map=model_colour_scheme,
    points=False,
    title="Distribution of L2 Errors by Model"
)

box_fig2.update_layout(xaxis_title="L2 Error", yaxis_title="Model Type",xaxis=dict(showgrid=True),showlegend=False)
st.plotly_chart(box_fig2, use_container_width=True)

# Histogram
st.header("3. Error Frequency Histogram")
st.caption("Comparitive histogram of L2 error frequencies. The plot can be filtered by the legend on the side for individual models.")

# Control the zooming by limiting X
x_limit = all_sample_df['error_l2'].quantile(0.95)

hist_fig3 = px.histogram(
    all_sample_df,
    x="error_l2",
    color="model_type",
    color_discrete_map=model_colour_scheme,
    barmode="overlay", #see-through
    opacity=0.6,
    nbins=50,
    title="Density of L2 Errors"
)

hist_fig3.update_layout(xaxis_range=[0, x_limit], xaxis_title="L2 Error", yaxis_title="Count",legend_title_text="Model")
st.plotly_chart(hist_fig3, use_container_width=True)

st.markdown("---") #line to sep graphs

# Scatter Plot
st.header("4. Scatter Plot Analysis")
st.caption("Ground Truth Coordinates coloured by L2 Error Magnitude.")

# Dropdown
models_list = sorted(all_sample_df['model_type'].unique())
selected_model = st.selectbox("Select Model:", models_list)

# Filter Data
subset_df = all_sample_df[all_sample_df['model_type'] == selected_model]

 
# Blue/red scale to display scale/magnitde of L2 error
scatter_fig4 = px.scatter(
    subset_df,
    x="gt_x",
    y="gt_y",
    color="error_l2",
    color_continuous_scale="RdBu_r",
    hover_data=["game_id", "play_id", "frame_id"], #hover tooltip
    title=f"Error Plot: {selected_model}"
)

# Fix Aspect Ratio
scatter_fig4.update_yaxes(
    scaleanchor="x",
    scaleratio=1
)
scatter_fig4.update_layout(xaxis_title="Ground Truth X", yaxis_title="Ground Truth Y", coloraxis_colorbar=dict(title="L2 Error"))

st.plotly_chart(scatter_fig4, use_container_width=True)

st.markdown("---") #line to sep graphs

# Line Chart (Error over Frame ID)
st.header("5. Error Over Frame Analysis")

# Agg using frame as proxy for time
time_df = all_sample_df.groupby(['model_type', 'frame_id'])['error_l2'].mean().reset_index()

line_fig5 = px.line(
    time_df,
    x="frame_id",
    y="error_l2",
    color="model_type",
    color_discrete_map=model_colour_scheme,
    title="Average L2 Error Over Time (Frame ID)"
)

line_fig5.update_layout(xaxis_title="Frame ID (Time)", yaxis_title="Average L2 Error",legend_title_text="Model")
st.plotly_chart(line_fig5, use_container_width=True)


# Display the dataframe
with st.expander("View Underlying Prediction Data"):
    st.markdown("Inputs and Prediction used to train the model")
    st.dataframe(all_sample_df)
